name: riverpod2
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  cloud_firestore: ^4.8.0
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutterfire_json_converters: ^0.0.7
  freezed_annotation: ^2.4.1
  go_router: ^10.1.2
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  build_runner: ^2.4.4
  riverpod_generator:
  freezed: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
